language: php
php:
    - 5.4
    - 5.5
    - 5.6

branches:
    only:
        - master

matrix:
    include:
        - php: 5.4
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.5
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: 5.6
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'

before_script:
    - composer update --prefer-source --dev

script:
    - bin/phpspec run -fpretty
    - bin/php-cs-fixer --diff --dry-run -v fix --config-file .php_cs
