services:
    knp_rad_fixtures_load.loader:
        class: 'Knp\Rad\FixturesLoad\Loader'
        arguments:
            - '@doctrine'
            - '@knp_rad_fixtures_load.fixtures_factory'
            - '@event_dispatcher'

    knp_rad_fixtures_load.fixtures_factory.legacy_factory:
        class: 'Knp\Rad\FixturesLoad\FixturesFactory\LegacyFactory'

    knp_rad_fixtures_load.fixtures_factory.persister_factory:
        class: 'Knp\Rad\FixturesLoad\FixturesFactory\PersisterFactory'

    knp_rad_fixtures_load.reset_schema_processor:
        class: 'Knp\Rad\FixturesLoad\ResetSchemaProcessor'
        arguments:
            - '@doctrine'
